select * FROM TRANSACTIONS
SHOW INDEXES FROM CUSTOMERS;

create INDEX LAST_NAME
ON CUSTOMERS(LASTNAME,FIRSTNAME);

select * FROM CUSTOMERS
WHERE FIRST_NAME = "POPPY";

create INDEX LAST_NAME_FIRST_NAME
ON CUSTOMER(LAST_NAME,FIST_NAME);

SHOW indexes FROM CUSTOMERS;

ALTER TABLE CUSTOMRS
DROP INDEX LAST_NAME_IDX;





