INSERT INTO TRANSACTIONS(AMOUNT,CUSTOMER_ID)
values(1.00,NULL);
SELECT * FROM TRANSACTIONS;

insert INTO CUSTOMERS(FIRST_NAME,LAST_NAME)
values("POPPY","PUFF");

SELECT * FROM CUSTOMERS;

SELECT *
FROM TRANSACTIONS INNER JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

SELECT TRANSACTIOM_ID,AMOUNT,FIRST_NAME,LAST_NAME
FROM TRANSACTIONS INNER JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

SELECT *
FROM TRANSACTIONS LEFT JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

SELECT *
FROM TRANSACTIONS RIGHT JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

