CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY auto_increment,
FIRST_NAME varchar(50),
LAST_NAME VARCHAR(50));

select * FROM CUSTOMERS;

INSERT INTO CUSTOMERS(FIRST_NAME,LAST_NAME)
VALUES("FRED","SINGH"),
("ASHU","GUPTA"),
("SHIVAM","SINGH");

DROP TABLE TRANSACTIONS;

CREATE TABLE TRANSACTIONS(
TRANSACTION_ID INT PRIMARY KEY auto_increment,
AMOUNT DECIMAL(5,2),
CUSTOMER_ID INT,
foreign key(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID));

SELECT * FROM TRANSACTIONS
SELECT * FROM CUSTOMERS

INSERT INTO TRANSACTIONS(AMOUNT,CUSTOMER_ID)
VALUES(4.99,3),
(2.77,5),
(7.97,6);

DELETE FROM CUSTOMERS
WHERE CUSTOMER_ID = 3;




