CREATE TABLE PRODUCTS_ITEMS(
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(35),
PRICE DECIMAL(4,2) default 0
);

select * FROM PRODUCTS_ITEMS;

INSERT INTO PRODUCTS_ITEMS(PRODUCT_ID,PRODUCT_NAME)
VALUES(101,"STRAW"),
(102,"STICK"),
(103,"FORK");

SELECT * FROM PRODUCTS_ITEMS;

create TABLE TRANSACTIONS(
TRANSACTION_ID INT,
AMOUNT DECIMAL(5,2),
TRANSACTION_DATE datetime default now());

INSERT INTO TRANSACTIONS(TRANSACTION_ID,AMOUNT)
VALUES(2,5.99);

SELECT * FROM TRANSACTIONS;
DROP table TRANSACTIONS;



