create TABLE TRANSACTIONS(
TRANSACTION_ID INT primary key,
AMOUNT DECIMAL(5,2),
TRANSACTION_DATE datetime default now());

ALTER TABLE TRANSACTIONS
ADD constraint
primary key(AMOUNT);

INSERT INTO TRANSACTIONS(TRANSACTION_ID,AMOUNT)
VALUES(1000,4.99);

SELECT * FROM TRANSACTIONS;
DROP TABLE TRANSACTIONS;

create TABLE TRANSACTIONS(
TRANSACTION_ID INT primary key auto_increment,
AMOUNT DECIMAL(5,2),
TRANSACTION_DATE datetime default now());


INSERT INTO TRANSACTIONS(AMOUNT)


value(5.99);
SELECT * FROM TRANSACTIONS;

