SELECT * FROM EMPLOYEES
ORDER BY LAST_NAME DESC;

SELECT * FROM EMPLOYEES
ORDER BY LAST_NAME ASC;

SELECT * FROM EMPLOYEES
ORDER BY FIST_NAME DESC;

SELECT * FROM TRANSACTIONS
ORDER BY AMOUNT ASC,CUSTOMER_ID desc;

